README.md

Part of https://github.com/libp2p/website/issues/8.

Standardize README and add CC License

---

relay/README.md

Add js and go implementations, update multicodec

---

relay/README.md

@diasdavid this is just a temporary note while the review and update is in progress -- to prevent confusion and wasted effort on the part of others.

relay: add note about in-progress review and update

---

relay/README.md

add STOP_RELAY_REFUSED and MALFORMED_MESSAGE

---

2-state-of-the-art.md
4-architecture.md
6-interfaces.md

Thanks for the great work, gentlemen!

Fix various typos in the specification

---

5-datastructures.md

Update old addresses

---

4-architecture.md

https://github.com/libp2p/go-floodsub/pull/79

Update implementations section. Merge this once #79 is merged

---

pubsub/gossipsub/README.md

iniates -> initiates
peformed -> performed

Fix wrong spellings

---

README.md

It's not much, but figured I'd fix it as long as I was scrolling by :).
Cheers!

Fix minor typo/link

---

pubsub/README.md
pubsub/gossipsub/README.md
pubsub/gossipsub/episub.md

The long awaited gossipsub spec has arrived.

gossipsub spec

---

pubsub/README.md

From https://github.com/libp2p/specs/pull/94#issue-220572669.

Add a note on using different kinds of topicIDs

---

pubsub/gossipsub/README.md

Minor modification to the gossipsub spec.

Close #129. Minor modification to gossipsub spec - emission of gossip.

---

pubsub/gossipsub/README.md

I asked about the Ambient Peer Discovery section in gossipsub in issue #125. @raulk responded with a more details explanation. I added the clarifications to the gossipsub specification.

Added a clarification to the Ambient Peer Discovery section

---

pubsub/README.md

pubsub: specify validator functions

---

mplex/README.md
pubsub/README.md
relay/README.md

Thanks @kpp for finding these.
Closes #153, #154, #155

Fix broken links

---

connections/README.md

Hey, saw a couple spelling changes to make in the connections readme. Thanks, loving this spec.

connections readme: spelling

---

README.md

readme: fix link to pnet spec

---

pubsub/gossipsub/README.md

@raulk @vyzo 
For https://github.com/libp2p/go-libp2p-pubsub/pull/204

Reflect the predicate adjustment in peer filtering for emitting gossip

---

noise/README.md

noise spec: add new IG members.

---

noise/README.md

Fixes to section links and some minor wording changes

Fixes to section links and some minor wording changes

---

discovery/mdns.md
relay/README.md

part of https://github.com/libp2p/libp2p/issues/79

fix: finish ipfs -> p2p multiaddr switch

---

pubsub/gossipsub/README.md

Update implementation status of `gossipsub-js`

chore: gossipsub js status update

---

pubsub/gossipsub/gossipsub-v1.1.md

Updates the gossipsub v1.1 spec to document/specify new behaviours introduced and tested in the reference implementation.

gossipsub v1.1 draft r2

---

pubsub/gossipsub/gossipsub-v1.1.md

This adds extended validators to the specification of gossipsub v1.1
see https://github.com/ethereum/eth2.0-specs/issues/1761

extended validators for gossipsub v1.1

---

pubsub/gossipsub/README.md

All versions of the logo at http://ipfs.io/ipfs/QmYv9CCtcvUZQmwnRYiNQ8UqTDRpL3ARe7h6e4qHESi47C

docs: add logo!

---

pubsub/gossipsub/gossipsub-v1.1.md

A few minor typos fixed throughout.

minor typos fixed

---

pubsub/gossipsub/gossipsub-v1.1.md

To support https://github.com/libp2p/go-libp2p-pubsub/pull/374 and https://github.com/libp2p/go-libp2p-pubsub/issues/368.

gossipsub: add slack before attempting to re-graft after being pruned.

---

pubsub/gossipsub/gossipsub-v1.1.md
pubsub/gossipsub/red.md

Updates the specification for the circuit breaker implemented in https://github.com/libp2p/go-libp2p-pubsub/pull/384

gossipsub v1.1: Validation queue protection with Random Early Drop

---

README.md

Addresses https://github.com/libp2p/specs/issues/281

Update README being explicit about proto2

---

rendezvous/README.md

This is the follow-up PR mentioned in https://github.com/libp2p/specs/pull/334#issuecomment-865456270.
Relates to https://github.com/libp2p/specs/pull/334.
Fixes https://github.com/libp2p/specs/issues/337.

Remove PoW from the spec

---

relay/circuit-v2.md

fix spelling in circuit-v2

---

relay/circuit-v2.md

Spelling (#378)

---

relay/circuit-v2.md

A few things I noticed while reading through the spec.
Not sure if we want to bump the revision for such minor fixes? Can always drop the last commit!

relay/circuit-v2: Do minor fixes

---

ROADMAP.md

I would like to propose (a) including _automated compatibility testing_ into our roadmap and (b) prioritizing it within the _Evolve_ section.
What do folks think?

ROADMAP: Add section on "Automated compatibility testing"

---

autonat/README.md

Note that this pull request does not target `master` but the `autonat` branch.

autonat/README: Add TOC and describe stream lifecycle

---

ROADMAP.md

Mark two main work items on Roadmap as "in progress".
(As discussed in past call with Steve.)

ROADMAP.md: Mark global connectivity and testing as in progress

---

README.md

Update protocol section, listing autonat, mdns, noise and dcutr.

README.md: Update protocol section

---

pubsub/README.md

pubsub: clarify stream management

---

_archive/4-architecture.md
_archive/5-datastructures.md

_archive/: Fix links to non archived resources #444

---

ROADMAP.md

- Add core tenets
- move Wasm to short term goals

roadmap: add core tenets

---

addressing/README.md
autonat/README.md
connections/hole-punching.md
relay/DCUtR.md
relay/circuit-v2.md
tls/tls.md
webrtc/README.md
webtransport/README.md

* Corrected a few lifecycle stages: addressing, autonat, hole-punching (1A -> 3A), WebTransport (1A -> 2A)
* DCUtR to Recommendation (from Working Draft)
* circuit-v2 to Recommendation (from Draft)
* TLS to Recommendation (from Candidate Recommendation)

chore: update lifecycle and maturity

---

00-framework-02-document-header.md
addressing/README.md
autonat/README.md
connections/README.md
connections/hole-punching.md
connections/simopen.md
discovery/mdns.md
fetch/README.md
identify/README.md
kad-dht/README.md
mplex/README.md
noise/README.md
plaintext/README.md
pnet/Private-Networks-PSK-V1.md
pubsub/README.md
pubsub/gossipsub/gossipsub-v1.0-old.md
relay/circuit-v1.md
relay/circuit-v2.md
rendezvous/README.md
tls/tls.md

Follows https://github.com/libp2p/specs/pull/490#discussion_r1041308345

fix: minor grammar update for lifestyle doc phrase 

---

yamux/README.md

Resolves https://github.com/libp2p/specs/issues/471.
cc (Interest-group) @mxinden @marten-seemann @wemeetagain @ianopolous

yamux: recommend buffering of inbound streams

---

connections/simopen.md

deprecate multistream simopen

---

pubsub/gossipsub/gossipsub-v1.1.md

Just some small things I saw while reading through the spec

docs: update spelling in GossipSub-v1.1

---

webrtc/webrtc.md

This PR adds a sequence diagram based on the spec description

feat: add webrtc sequence diagram

---

pubsub/gossipsub/implementation-status.md

of Gossipsub versions and extensions.

gossipsub: Add table to track implementation status
