libp2p/specs

7-properties.md

Its less confusing, there are other multiplexers with different names, shortening it to mplex both distinguishes itself as its own protocol, and saves bytes.
Plus, this is already in go-ipfs as /mplex

Change 'multiplex' multistream id to 'mplex'

---

3-requirements.md
4-architecture.md
7-properties.md
relay/README.md
transports/circuit-relay.md

Review of the spec itself concluded in libp2p/go-libp2p-relay#1 -- the additional changes in this PR are purely linking it into place.
I chose to categorize the relay primarily as a transport, since that is what it looks like to the layers using it -- you use it by means of `/p2p-circuit` multiaddrs, just like other transports. The fact that it's also a swarm protocol is an implementation detail from this point of view.

Add and link circuit relay spec

---

3-requirements.md

This heading was at a higher level than the others, making the later headings look like subheadings.

Make heading levels match

---

relay/README.md

It took me a while to realize that a relay it's not just
tunneling a stream to a destination through a proxy peer
but rather it is making a destination peer
aware that the source peer is reachable through the relaying
node. Hopefully this makes that more explicit.
License: MIT
Signed-off-by: Hector Sanjuan <code@hector.link>

Clarify the difference between a tunnel and a relay

---

relay/README.md

Reviewed the wire protocol section. There were some incoherences in the high-level order of events and some question marks everywhere, I fixed them based on commons and our conversations.

review Wire protocol section from the relay spec

---

relay/README.md

As promised on Friday, July 8, I've cleaned up, coalesced and added what was missing to the Relay spec, taking the bits from PRs #18 and #15 and all the comments. 
Hope you enjoy :)

The Circuit Relay Specification

---

relay/README.md

I think it would be very useful for relays to have a way to signal to their clients that they are overloaded or want to temporarily stop relaying new connections. I think that a simple response code like this is sufficient at the protocol level to allow various load management strategies to be implemented.

RFC: Add relay backoff code

---

4-architecture.md
pubsub/README.md
pubsub/gossipsub/README.md

This is taken from libp2p/research-pubsub#17, with a few logistical changes that are all contained in the last commit.
It's fine that this isn't a perfect spec document yet -- not letting important information rot in issues and PRs is one step towards better documentation :)

gossipsub: work draft 1 into the specs 

---

pubsub/README.md

We need to also add a way to use a `topicID` (in a forward and backward compatible way?).
You could just use `TopicDescriptor.name`.
Edit: for future compatibility with using a CID I suggest using an enum, `TopicID`, that contains the name. Then when a topic CID is implemented that can be added to enum. That at least works well for Rust, although I'm not sure about Go and JS. I could add that to the spec.

Add a note to say that `TopicDescriptor` isn't used

---

rendezvous/README.md

Only thing I can see missing is adding the `E_UNAVAILABLE` which will be used when registrations are happening too fast or it's generally overloaded with the already registered clients.
Previous: https://github.com/libp2p/specs/pull/44 (mostly doesn't load)

RFC: rendezvous

---

pubsub/README.md

I would like to propose adding specific data types for the pubsub protocol such that new implementations are interoperable with current implementations (specifically the go implementation). 
This example specifies the protobuf bytes `sequence_number` of pubsub to be a 64-bit big-endian uint as is implemented in the go-implementation. 
If this is desired, I can continue this PR with all other information that is sent across the wire using the go-implementation as the standard.

Specify specifc types for implementation interoperability

---

2-state-of-the-art.md

Add [NDISC] and [DHCPv6] to the section discussing existing
protocols.
[NDISC]: https://tools.ietf.org/html/rfc4861
[DHCPv6]: https://tools.ietf.org/html/rfc3315

Add protocols for IPv6 address resolution

---

pubsub/README.md

Adds message signing details in the pubsub spec, as implemented in go.

pubsub: message signing specification

---

mplex/README.md

The first commit copy-pastes the specs from https://github.com/libp2p/mplex
This repo should be deleted after this PR is merged.
The second commit adds my changes.
Most notably, I tried to clarify some ambiguities remaining after https://github.com/libp2p/mplex/pull/3
cc @Stebalien

Add specs for mplex

---

1-introduction.md
4-architecture.md
6-interfaces.md
7-properties.md

This adds some warning text to a few sections of the main specs document to signal that we're aware of its shortcomings and are working on improving the spec. The odd formatting is me abusing github markdown's table syntax to draw some attention to the text.
So far I've just added a pretty generic notice to the intro and the sections that seem (to me) to be the most problematic: architecture, interfaces and properties.
There are other sections that need work as well, but those three need the most attention in the short term, IMO.
Questions:
- do we agree that these sections should be considered deprecated?
- what other parts of the spec should have "warning notices"?
- right now all the notices link to #156 - perhaps it would be better to make one issue per document to track ideas for …

Add initial deprecation notices

---

tls/design considerations.md
tls/tls.md

In the last couple of weeks I spent a lot of time designing a TLS 1.3 based handshake for libp2p. This document has come a long way, and I managed to remove a lot of the complexity, while at the same time preserving the future extensibility which I originally built into this version of the protocol.
This is a proposal how we can run the libp2p handshake using TLS 1.3 in the future. Since we're currently only using secio in production, we are completely free to design things the way we want, without having to worry about backwards compatibility. That means that **now** is the right time to criticize every single aspect of this protocol.
I already implemented a proof of concept in https://github.com/libp2p/go-libp2p-tls/pull/20, feel free to play around with that code as well.

libp2p TLS 1.3 Handshake

---

4-architecture.md
discovery/mdns.md

Background discussion at [Future of mDNS discovery](https://github.com/libp2p/libp2p/issues/28)

[RFC] peer discovery with mDNS

---

00-framework-02-document-header.md

Following up with #169, this adds a spec for a small header to put at the top of our spec documents to convey the current lifecycle information, spec authors & interest group.
I've added these to the [peer id](https://github.com/libp2p/specs/pull/100) and [secio](https://github.com/libp2p/specs/pull/106) spec PRs, if anyone wants to see a real-world example.
In the spirit of the new lifecycle framework, I set the maturity level for this PR to `Working Draft`, so we can try sending this through the whole process.
Who wants to be in the Interest Group for this?

libp2p specs framework: document header format

---

README.md
discovery/mdns.md
identify/README.md
mplex/README.md
pnet/Private-Networks-PSK-V1.md
pubsub/README.md
pubsub/gossipsub/README.md
pubsub/gossipsub/episub.md
relay/README.md
rendezvous/README.md
tls/tls.md

Hey all, I've been going through the existing specs and trying to see how they fit to the lifecycle / maturity framework from #169.
Here's what I came up with:
| Spec       | Stage | Authors                         | Interest Group                                     |
|------------|-------|---------------------------------|----------------------------------------------------|
| mdns       | 3A    | @richardschneider               | @raulk, @daviddias                                 |
| identify   | 3A    | @vyzo                           | @tomaka, @richardschneider, @Stebalien, @bigs      |
| mplex      | 3A    | @daviddias, @Stebalien, @tomaka | @richardschneider, @jacobheun                      |
| pnet       | 3A    | @Kubuxu                         | @jacobheun, @lgierth, @daviddias …

Adapt existing specs to lifecycle framework

---

plaintext/README.md

This adds a spec for exchanging keys and peer ids when setting up the plaintext "security" protocol, as discussed in #184.
This sends both peer ids and keys as @raulk outlined - we could potentially just send the keys as in @Warchant's c++ implementation and derive the ids.
Also, I bumped the version in the protocol id, since it seems like sending the key message over will break anyone using the existing `/plaintext/1.0.0` protocol id.

Add draft spec for plaintext key exchange protocol

---

README.md

Just realized I forgot to add the plaintext spec from #186 to the README index.

add plaintext spec to index

---

noise/README.md

Hey all, this is what I've got so far to address #195 and specify a Noise security protocol for libp2p. It basically follows the outline I put in the [issue comments there](https://github.com/libp2p/specs/issues/195#issuecomment-517449710) and is very similar to the rust-libp2p implementation.
I'll fill in the Design Consideration sections soon, but didn't want to commit before we're done considering designs :)
Does this seem like a good direction? 
@raulk @tomaka @romanb - I added you all to the interest group. If anyone else wants in, let me know!

Draft of noise-libp2p spec

---

fetch/README.md

This is an initial stab at putting together a spec for the `Fetch` protocol. As explained in the spec this protocol is basically just a simple network request for `Fetch(key) (value, statusCode)`.
The document contains both the answers to questions about a Working Draft and put together the spec outline (as detailed in the [lifecycle document](https://github.com/libp2p/specs/blob/master/00-framework-01-spec-lifecycle.md)).
^ @vyzo @raulk @Stebalien

[Working Draft] Fetch protocol spec

---

RFC/0001-text-peerid-cid.md
peer-ids/peer-ids.md

> **Important Note:** this is the first RFC ever, following "option 2" from https://github.com/libp2p/specs/issues/198  and creating a template for future RFCs as a side-effect. The goal is to kick-off the RFC process. I am not a native speaker, feel free to tweak sentences that sound weird.
The RFC 0001 aims to modify Peer ID spec to alter the default string   representation from Multihash to CIDv1 in Base32 and to support encoding/decoding text peerids as CIDs.
- <del>Added `RFC/0000-RFC-TEMPLATE.md` the TEMPLATE every future RFC should follow </del>
- Removed the template as suggested by @jacobheun – we will add it in separate PR after this PR is finalized
- Added `RFC/0001-text-peerid-cid.md`  the first RFC  to test the process
- Modified `peer-ids/peer-ids.md` to reflect changes from …

RFC 0001: Text Peer Ids as CIDs

---

secio/README.md

secio doesn't use varint when sending messages, this corrects the spec to be inline with current implementations.

fix: secio doesnt use varint

---

connections/multiselect2.md

To select the stream muxer, in #227, the server sends a list of supported stream muxers and lets the client pick one:
```
client                                                server
<- Offer [ A, B, C ]
*picks B* -> Use [ B ]
```
This can be done in parallel to the cryptographic handshake because we use Early Data, right after receiving the ClientHello. The list is encrypted with 1-RTT keys, but at this moment the server hasn't yet verified the client's identity. A similar reasoning applies to Noise handshakes.
@raulk remarked in his review of #227 that there's a different option (which we had discussed before, but which I hadn't included in the final proposal). The motivation is that #227 relies on assumptions about the cryptographic handshake (it's the server that's able to send Early …

select the stream muxers by intersecting the lists of supported muxers

---

secio/README.md

This is apparently already the case in practice, but we should add it to the specs.

Add a limit of 8MiB to secio messages size

---

peer-ids/peer-ids.md

* I reorganized it to put all the key encoding logic together (instead of sticking the peer ID stuff in the middle).
* Described how the protobufs must should be deterministically encoded.
* Fixed some misconceptions around CIDv0 versus CIDv1. Qm... peer IDs are not CIDv0, they're just bare multihashes.
* Instructed users to continue encoding peer IDs as bare multihashes by default for now. Not all implementations support decoding CID peer IDs.

refactor the peer ID spec

---

discovery/mdns.md

A Recommendation has at least TWO implementations demonstrating interoperability.
A Candidate Recommendation has ONE implementation serving as the Reference Implementation.
This mDNS spec currently has no known libp2p implementations.
mDNS support in go-libp2p and js-libp2p are non-compliant because they predate this spec, and this spec introduces breakages.
Hence, as per above, we demote this specification to the maturity stage it belongs to: Working Draft.

demote mDNS spec to Working Draft.

---

noise/README.md

Following from the discussion in #234, we've abandoned the "handshake seal" construction, as it is considered redundant. This PR carries forward the other changes introduced in that PR, for inclusion in the spec.
Concretely, this PR simplifies protobuf field naming, and formalises in which Noise messages of IK and XX the message payload is to be shared, to guarantee secrecy, integrity and authentication.
Since these changes have been reviewed in past iterations with no comments, I will merge this PR in 24h unless somebody screams.
ping: @shahankhatch @Mikerah @djrtwo @dryajov @mpetrunic @morrigan @araskachoi @mhchia

noise spec: various refinements.

---

pubsub/gossipsub-wip.md

This is some very early revision & restructuring of the gossipsub spec to try to make it a bit more normative and clarify a few things. So far it's mostly a skeleton - I've been writing in a separate markdown doc and copying things over and tweaking as I go. I've kept most of @vyzo's writing but have made some changes here and there.
@vyzo there's one change that I want to get your opinion on.  I personally like how you build up a progression from floodsub -> randomsub -> meshsub -> gossipsub, but I think it might be confusing for readers looking for a straightforward normative description of what gossipsub is and how to implement it. 
In what I've got so far, I jump directly from floodsub to gossipsub - to me this feels a bit clearer than naming randomsub and meshsub and describing them …

revise gossipsub spec

---

pubsub/gossipsub/gossipsub-v1.1.md

This adds a few typo edits, links and formatting, plus a bit more detail around parameter decay. I also added some clarification that flood publishing applies even if you're subscribed to a topic (hope that's correct @vyzo).
The big thing is a section that lists all the new configurable parameters in one place, which I think will be nice for implementors.

Small edits to gossipsub v1.1  & list of new parameters

---

pubsub/gossipsub/gossipsub-v1.1.md

It occludes the logic as it is now and dumps too much information without context at the beginning of the document.

gossipsub v1.1: move overview of new parameters to the end of the document

---

noise/README.md

This PR removes Noise Pipes from the noise-libp2p spec, and also removes the padding within encrypted payloads. 
Apologies to anyone who was waiting on this or was confused about the current state of the spec; this took me a lot longer than it should have :)
These changes bring the spec in line with the current Go and JavaScript implementations.
cc noise-libp2p IG: @raulk, @tomaka, @romanb, @shahankhatch, @Mikerah,
@djrtwo, @dryajov, @mpetrunic, @AgeManning, @morrigan, @araskachoi,
@mhchia

remove Noise Pipes and padding within payloads

---

pubsub/gossipsub/gossipsub-v1.1.md

Updates the gsv1.1 spec:
- Prune backoff is now specified aspart of the protobuf `PRUNE` message.
- P4 is now quadratic
- P7 is introduced for behavioural penalties
- IHAVE flood spam protection measures are specified

Update gossipsub v1.1 spec

---

pubsub/gossipsub/gossipsub-v1.1.md

Fixes a number of global score parameters specified in The Score Function section. It's been set to `2` while there are `3` of them in the score function.

Fix number of global score params

---

pubsub/gossipsub/gossipsub-v1.1.md

Specifies outbound connection qutoas, as implemented in https://github.com/libp2p/go-libp2p-pubsub/pull/339

Update gossipsub v1.1 spec for outbound quotas

---

pubsub/gossipsub/gossipsub-v1.1.md

The basic premise is bootstrapper PX instead of peer discovery services.

Update gossipsub v1.1 spec with recommendations for network bootstrapping

---

pubsub/gossipsub/README.md

Gossipsub repo url changed from `ChainSafe/gossipsub-js` to `ChainSafe/js-libp2p-gossipsub`
Also gossipsub v1.1 implementation is in progress

chore: update gossipsub js impl info

---

pubsub/gossipsub/gossipsub-v1.1.md

Adds a paragraph in the recommendation for network operators to emphasize the necessity of secure peer discovery.

Update gossipsub v1.1 spec with recommendation for secure bootstrapping

---

pubsub/gossipsub/gossipsub-v1.1.md

Reference implementation is https://github.com/libp2p/go-libp2p-pubsub/, conformant to the promoted spec as of https://github.com/libp2p/go-libp2p-pubsub/pull/263, and follow-ups.

Promote gossipsub v1.1 spec to Candidate Recommendation

---

pubsub/README.md
pubsub/gossipsub/README.md

I noticed there was a room in the PubSub specs for implementation, but a lot of implementations (see Eth2) seems to be missing. Added nim-libp2p as that's the one I'm currently using :)

Update PubSub with nim-libp2p implementations

---

pubsub/README.md

Small tweak, but it kept jumping out at me as I'm reading the spec. A spec should be written in an authoritative manner and not second-guess itself. Right now it reads more like a note to self that was left over.
If this is a possible enhancement/renaming, it should be captured in a separate issue IMO.
It is also unlikely that this field will change, considering how many clients implemented it with this naming.
Finally, I personally think the name is perfectly fine :)

PubSub: Remove second-guessing naming of Message field

---

pubsub/gossipsub/gossipsub-v1.0.md

Rationale:
- go-libp2p currently produces non-utf8 strings
- making this bytes allows more flexibility in creating message ids, e.g.
- random bytes
- hashes
This issue was discovered in https://github.com/libp2p/rust-libp2p/issues/1671 . There is a coresponding issue in go-ipfs-pubsub, https://github.com/libp2p/go-libp2p-pubsub/issues/361
Changing this should have no negative impact. Implementations that expect valid utf-8 strings are already broken, because go-ipfs emits non utf8 strings. See https://github.com/libp2p/go-libp2p-pubsub/issues/361#issuecomment-663569492

Make messageIDs bytes instead of strings

---

noise/README.md

This spec now satisfies the conditions to be considered an ACTIVE RECOMMENDATION.
The two known interoperable implementations are:
* go-libp2p-noise: https://github.com/libp2p/go-libp2p-noise
* js-libp2p-noise: https://github.com/NodeFactoryIo/js-libp2p-noise
---
ping @raulk, @tomaka, @romanb, @shahankhatch, @Mikerah, @djrtwo, @dryajov, @mpetrunic, @AgeManning, @morrigan, @araskachoi, @mhchia
Conformant to our [spec lifecycle process](https://github.com/libp2p/specs/blob/master/00-framework-01-spec-lifecycle.md), you have 10 days to dispute the promotion ;-)

promote noise-libp2p spec to maturity stage 3A

---

noise/README.md

This just corrects the maturity label, it should be `Recommendation` per the lifecycle change to 3A via https://github.com/libp2p/specs/pull/263.

fix(noise): correct the maturity label to match the lifecycle stage

---

pubsub/gossipsub/gossipsub-v1.1.md

Nominating gossipsub developers from other libp2p implementations that Eth2 uses to be notified of changes in the gossipsub spec: @protolambda, @djrtwo, @dryajov, @mpetrunic, @AgeManning, @Nashatyrev, @mhchia.

gossipsub: add eth2 developers to interest group.

---

pubsub/gossipsub/README.md

[js-libp2p-gossipsub](https://github.com/ChainSafe/js-libp2p-gossipsub) had Gossipsub1.1 released in `libp2p-gossipsub@0.6.0` and is supported from `libp2p@0.29.x` is JS 🎉

chore: update js gossipsub implementation status to complete

---

pubsub/README.md
pubsub/gossipsub/gossipsub-v1.1.md

This introduces editorial changes on top of #294. We now concentrate all our additions in `pubsub.md`.
---
@protolambda, I wanted to target your branch, but it's in a fork.
cc @arnetheduck

pubsub: signing policy -- #294 + editorial changes

---

pubsub/README.md
pubsub/gossipsub/gossipsub-v1.1.md

See https://github.com/libp2p/go-libp2p-pubsub/pull/359 for motivation and related discussion.
In short: Eth2 uses content-addressing and does not use these fields. If not content-addressed, signature data should be verified more strictly.
Changes:
- Pubsub readme: 
- Describe the optionality of singing in the relevant signing section of pubsub, and refer to new gossipsub v1.1 configuration option
- Clarify that signatures are singing over all fields (incl unrecognized fields)
- Gossipsub v1.1:
- Briefly describe the general two cases when the fields are desired or not.
- Document legacy "lax" behavior may be implemented as additional signing policies
- Document two main (strict) signing policies
- Feedback wanted: best way to describe the rejection of messages with bad signature or …

gossipsub v1.1: introduce message signing policy

---

pubsub/gossipsub/gossipsub-v1.0.md

Totally trivial PR to fix 2 `'` typos.

2 one-char typo fixes.

---

rendezvous/README.md

This PR adds the SignedPeerRecord to the Register message.
Since this is still a Working Draft spec, there are a few things that I would like to suggest:
- I think we should drop the `PeerInfo` message and just use the `SignedPeerRecord`
- Should we add a limit in the size of a namespace to register?

fix: rendezvous spec

---

relay/README.md

Currently, the `Status` enum has `SUCCESS` as the name of the 100 status code, but the explanations of phases II and III use `OK` instead.

Consistent `SUCCESS` for relay status code

---

plaintext/README.md

Make clear that only the plaintext protocol handshake messages are
length prefixed, not the actual user level data send via a negotiated
plaintext protocol connection.
See https://github.com/libp2p/rust-libp2p/issues/1760 for details.

plaintext: Clarify only handshake messages being framed

---

secio/README.md

The SECIO security transport has been deprecated [1]. This commit
updates the specification accordingly.
> The transition from the `Active` status to the `Deprecated` status is
performed via a *Pull Request* that is reviewed by the _Interest Group_,
allowing 5 working days to elapse to collect feedback from the libp2p
community at large.
As per the specification life cycle specification I am requesting a review
from @Stebalien, @richardschneider, @tomaka and @raulk.
[1] https://blog.ipfs.io/2020-08-07-deprecating-secio/

secio: Transition SECIO spec from Active to Deprecated

---

pubsub/gossipsub/README.md

With https://github.com/libp2p/rust-libp2p/pull/898 and https://github.com/libp2p/rust-libp2p/pull/1720 I think it is safe to say that the Rust GossipSub v1.0 implementation is complete.
@AgeManning please correct me in case I am missing something.

pubsub/gossipsub/README: Mark rust gossipsub v1.0 as complete

---

connections/README.md

Fixes https://github.com/libp2p/specs/issues/297.

connections/README: Add missing link to resource manager issue

---

mplex/README.md

NOTE: go-mplex _technically_ supports 61bit IDs, but those violate our unsigned-varint spec and may not work on all implementations.
fixes #259

fix: specify max mplex stream ID size

---

relay/README.md

rust-libp2p implements the circuit relay v1 specification since https://github.com/libp2p/rust-libp2p/pull/1838.

relay/README: Add rust-libp2p to list of implementations

---

connections/simopen.md

_Note this does not target the `master` branch but the `rfc/multistream-simopen`
branch._
In order to be backwards compatible with vanilla multistream-select the
simultaneous open extension disguises its identifier as a protocol ID.
According to the protocol negotiation specification protocol IDs can use any
string, though by convention they are prefixed with a '/'.
> Each protocol supported by a peer is identified using a unique string called a
protocol id. While any string can be used, the conventional format is a
path-like structure containing a short name and a version number, separated by
/ characters. For example: /mplex/1.0.0 identifies version 1.0.0 of the mplex
stream multiplexing protocol. multistream-select itself has a protocol id of
/multistream/1.0.0. …

connections/simopen: Prefix fake protocol ID with a '/'

---

mplex/README.md

This reverts commit 51ec3e5ab16858c7d2e9b9bfb15074aba886c8f0.
See the discussion starting at:
https://github.com/libp2p/specs/pull/317#issuecomment-826362668

Revert "mplex: allow for 28bit stream IDs."

---

rendezvous/README.md

This PR adds recommendations to the rendezvous spec regarding how a rendezvous point should be configured. These were based on the discussions on the go implementation PR and current code. The discover limit seems a bit higher, but if we have smaller defaults on the client, we can keep it as 1000.
It also fixes an error response status to `E_INVALID_SIGNED_PEER_RECORD` since we are using signed peer records now and this is now yet implemented.

chore: add rendezvous recommendations

---

identify/README.md

> Note on asymmetrical protocols: Assume an asymmetrical
request-response style protocol `foo` where some clients only support
initiating requests while some servers (only) support responding to
requests. To prevent clients from initiating requests to other clients,
which given them being clients they fail to respond, clients should not
list `foo` in their `protocols` list.
Question emerged in https://github.com/libp2p/specs/issues/324.

identify: Document identify behavior for asymetrical protocols

---

peer-ids/peer-ids.md

* This is just fixing typo in the `peer-ids` document.

fix typo in peer-ids.md

---

connections/README.md
connections/hole-punching.md

Extend connections specification with a document describing the long
term vision of hole punching in libp2p across transport protocols,
platforms and implementations.
(For now) this is a high level description only. I hope for this document to (A)
help guide the various libp2p hole punching approaches to share sub protocols
and thus achieve greater interoperability and (B) paint the greater picture for
newcomers.
I appreciate feedback of all forms.

connections: Add hole punching vision document

---

RFC/0002-signed-envelopes.md
RFC/0003-routing-records.md

These protobuf definitions are taken from the go-libp2p repo.
Fixes #329.
cc @mxinden

Update Envelope and PeerRecord protobufs to latest version

---

rendezvous/README.md

To be meaningful, TTL has to be a positive integer hence the use of
an signed integer does not bring any value and only introduces
unnecessary error handling.

[Rendezvous] Change `ttl` and `limit` to `uint64`

---

RFC/0003-routing-records.md
connections/hole-punching.md

With https://github.com/libp2p/specs/pull/108/ and https://github.com/libp2p/specs/pull/325 merged, we can reference the specifications directly, instead of their initial pull requests.

*: Update Kademlia and Circuit Relay v2 links

---

README.md
ROADMAP.md

This documents the libp2p short and long term roadmap based on
previous work (e.g. see [libp2p/libp2p/60], [ipfs/roadmap/18],
[libp2p/specs/archive]).
Feedback from the whole community is welcome.
Fixes https://github.com/libp2p/libp2p/issues/68.
[libp2p/libp2p/60]: https://github.com/libp2p/libp2p/issues/60
[ipfs/roadmap/18]: https://github.com/ipfs/roadmap/issues/18
[libp2p/specs/archive]: https://github.com/libp2p/specs/tree/master/_archive

ROADMAP.md: Add high level project roadmap

---

rendezvous/README.md

All connections in libp2p are authenticated. As such, we don't have
to include the PeerId in the `Unregister` message. We only allow
peers to unregister themselves and therefore, this `id` would always
be equal to the one we are learn from the authentication layer. Having
to compare those and ensure they are equal is an unnecessary error
path.
This also clarifies the absence of an `UNREGISTER` response.
Resolves #335.

[Rendezvous] Clarify `UNREGISTER` behaviour and remove `id` field

---

README.md
addressing/README.md

This is a spec on addressing I've been chipping away at for a while now. So far it covers how multiaddrs basically work, the rules for DNS resolution, and the address formats for (most) transports.
TODO:
Also TODO, but probably in a second pass:
- Add section about address discovery and exchange. This could potentially be where we spell out the abstract "peer routing" interface, which would be useful to xref from e.g. the DHT spec.
@Stebalien, the DNS resolution described here aligns with where you're going with this PR, I think: https://github.com/multiformats/go-multiaddr-dns/pull/17

Add spec on addressing & use of multiaddr

---

protocol-select/README.md

This PR goes with #353, and aim to split the multiaddr change into a separate change, unrelated to Protocol Select.

split the multiaddr change out of this spec

---

tls/tls.md

The go implementation uses `OCTET STRING` instead of `BIT STRING` for elements of `SignedKey`.
The options are:
1) fix the go implementation
2) update the specs
However with 1) we should also notify every implementors to fix it, e.g. https://github.com/alanshaw/js-libp2p-quic/blob/1f3c1dd6dff3c2e94710a1ae76e815e0805c8a99/src/crypto.js#L44

Fix tls.md

---

noise/README.md

The libp2p-noise specification states the following related to early data (payloads): 
```
These payloads MUST be inserted into the first message of the handshake pattern that guarantees secrecy.
In practice, this means that the initiator must not send a payload in their first message.
Instead, the initiator will send its payload in message 3 (closing message),
whereas the responder will send theirs in message 2 (their only message)
```
According to Noise XX security properties, the second message with payload provides forward
secrecy, however, the sender has not authenticated the responder, so this payload might be sent to any
party, including an active attacker. So an active attacker can just establish a connection with the
responder host and get the early data. 
So, this MR just …

Clarify properties of the libp2p-noise handshake's second message

---

identify/README.md

Previous versions of this specification required connections to be
closed on version mismatch. This requirement is revoked to allow
interoperability between protocol families / networks.
See https://github.com/libp2p/specs/issues/352 for the larger discussion.
Closes https://github.com/libp2p/specs/issues/352.

identify/: Don't close connection on protocol version mismatch

---

addressing/README.md
relay/circuit-v2.md

_Note: This pull request targets the `addresses-with-security-protocol` branch (https://github.com/libp2p/specs/pull/353) and not the `master` branch._
This patch addresses the problems below by detailing the solution below in the
corresponding specifications.
> Taxonomy:
>
> * `A`: The destination node.
>
> * `B`: The source node.
>
> * `R`: The relay node.
>
> * outer connection: The connection from `R` to `A`.
>
> * relayed (inner) connection: The relayed (inner) connection from `B` to
>   `A`.
>
>
> Problems we need to solve:
>
> 1. `B` and `A` need to know which security protocol to use to upgrade the
>    relayed (inner) connection.
>
> 2. In the case of active relaying, `R` needs to know which security
>    protocol to use to upgrade the outer connection to the destination.
>
> 3. …

*: Address security-protocol-in-multiaddr and relay conflict

---

tls/tls.md

This is a clarification how to marshal SubjectPublicKeyInfo according to the go implementation (https://github.com/libp2p/go-libp2p-tls/blob/7530faa07acbfc0aa918c072c2cb35d3c8d5d859/crypto.go#L143 and https://pkg.go.dev/crypto/x509#MarshalPKIXPublicKey).

Define precisely how to marshal SubjectPublicKeyInfo structure in tls.md

---

discovery/mdns.md

We don't use the `<peer-name>` for anything, we only should make sure that there's no collision in the network (I think). This was part of the initial design requirements: https://github.com/libp2p/libp2p/issues/28 (Proposal section).
Instead of figuring out how to best encode a peer ID such that it fits into 63 characters, a problem we've struggled with for a very long time, we can just admit that we're only filling this field because the RFC requires us to do so, and use random garbage.

use a random string as peer-name in mDNS

---

kad-dht/README.md

On PUT_VALUE the Golang implementation expects `key` on `Message` to
equal `key` on `Record` when handling a request (see [go-1]). This patch
updates the specification accordingly.
[go-1]: https://github.com/libp2p/go-libp2p-kad-dht/blob/7724838e46d1822b28fd20611ab9815d4ce2d94f/handlers.go#L151-L164
Caught by @pradt2 see https://github.com/libp2p/rust-libp2p/pull/2309.

kad-dht/README: Document key on Message during PUT_VALUE

---

pubsub/gossipsub/gossipsub-v1.1.md

This makes parameter names consistent with the rest of the spec

Fix typos in parameter names

---

relay/DCUtR.md

The `type` field of the DCUtR message definition should not be
`optional`, as a message without a `Type` is useless. Instead it should
be `required`.
See also circuit relay v2 specification using `required` for `type`.
```protobuf
message HopMessage {
enum Type {
RESERVE = 0;
CONNECT = 1;
STATUS = 2;
}
required Type type = 1;
```
```protobuf
message StopMessage {
enum Type {
CONNECT = 0;
STATUS = 1;
}
required Type type = 1;
```
If I am not mistaken, none of the libp2p implementations have released a DCUtR implementation yet, thus we can still easily make this change. Correct @marten-seemann?

relay/DCUtR: Make message type field `required`

---

ROADMAP.md

Over the past few months @marten-seemann and I have focused our engineering time on the "Unprecedented global connectivity" item through _Project Flare_. We have not yet started on "Low latency, efficient connection handshake" (aka. Protocol Select).
To make sure our roadmap reflects the above, this pull request swaps the two.

ROADMAP: Prioritize global connectivity over connection handshake

---

relay/circuit-v2.md

The Go implementation of the circuit relay v2 implementation treats the
`Reservation::expire` field as `required`:
``` Golang
result := &Reservation{}
result.Expiration = time.Unix(int64(rsvp.GetExpire()), 0)
if result.Expiration.Before(time.Now()) {
return nil, fmt.Errorf("received reservation with expiration date in the past: %s", result.Expiration)
}
```
https://github.com/libp2p/go-libp2p/blob/bfee9f593553b3cdaecc351f04b98aac78b8d8af/p2p/protocol/circuitv2/client/reservation.go#L88-L92
Where `rsvp.GetExpire` returns `0` when `Reservation::expire` is not set:
``` Golang
func (m *Reservation) GetExpire() uint64 {
if m != nil && m.Expire != nil {
return *m.Expire
}
return 0
}
```
https://github.com/libp2p/go-libp2p/blob/bfee9f593553b3cdaecc351f04b98aac78b8d8af/p2p/protocol/circuitv2/pb/ci …

relay/circuit-v2: Mark Reservation::expire as required

---

autonat/README.md

In order to uphoald the defense mechanism introduced in
048bdbfe2439058c355db612eac717fc8a46acbb one should not accept dial requests via
relayed connections.
Follow up on the discussion https://github.com/libp2p/specs/pull/362#issuecomment-978964384.
//CC @elenaf9

autonat/: Document denial of dial requests on relayed connections

---

kad-dht/README.md

This commit documents the DHT client mode, keeping routing tables clear
of clients (e.g. laptops), while still allowing clients to utilize the
functionality of the DHT.
A note on support across the implementations: Implemented in Go, pending in Rust (https://github.com/libp2p/rust-libp2p/issues/2032), uncertain about other languages.
//CC @aschmahmann and @MarcoPolo

kad-dht/README: Document client mode

---

pubsub/gossipsub/gossipsub-v1.1.md

1. Update `PublishThreshold` constraint in the table. This does not accurately reflect what the text says.
> `publishThreshold`: when a peer's score drops below this threshold, self published messages are not propagated towards this peer when (flood) publishing. This threshold should be negative, and **less than or equal** to the gossip threshold.
2. Change `IPColocationFactorThreshold` from a `Float` to an `Integer`. It does not make sense for this value to be a float. You cannot have a fractional "number of IPs a peer may have before being penalized."

Fix two minor gossipsub v1.1 spec problems

---

pubsub/gossipsub/gossipsub-v1.1.md

Noticed that these variables did not start with a capital letter like the other instances in the document.

Make gossip score vars start with uppercase letter

---

connections/README.md

The mplex multiplexer does not provide backpressure on a stream. Yamux does.
Given that this is a fundamental feature of a stream multiplexer, this commit
changes the spec to recommend yamux over mplex.
While yamux is not ideal, e.g. lacks backpressure on the connection level and
the number of streams, it is superior in all cases to mplex.
---
I don't think we should recommend mplex over yamux any longer. Thoughts?

connection/README: Recommend yamux over mplex

---

ROADMAP.md

My experimentation with WebTransport shows that there are no blockers to getting this implemented an rolled out. In fact, webtransport-go is able to communicate with browser nodes, and we have resolved the peer authentication issue in https://github.com/libp2p/specs/pull/404, even avoiding double encryption.
95% of the complexity of getting this implemented is on the Go side, and the remaining 5% on the JS side. If we want to prioritize this effort, the remaining work on the Go side is ~1-2 weeks, and 1-2 days on the JS side.
On the Rust side, this will probably be a lot harder to get going, considering that rust-libp2p doesn't have a QUIC implementation yet, let alone a WebTransport implementation. However, we don't need to implement this in rust-libp2p (for now), we can already reap the …

add the WebTransport effort to the roadmap

---

addressing/README.md

Fixed a typo in the addressing spec: The mandatory tcp port was omitted in one of the example addresses.

Fix Typo: Add missing tcp port in example address

---

ROADMAP.md

- Introduce "Done" section.
- Reduce scope of "Unprecedented global connectivity" to hole punching on QUIC
and TCP.
- Move item down to "Done" section.
Browser connectivity is tracked via https://github.com/libp2p/specs/pull/407/ and https://github.com/libp2p/specs/pull/414. I will add an additional pull request to track stream migration. Testing will be tracked via "Automated compatibility testing" section.
_As far as I remember, this is what we agreed on in Paris. Please correct me in case I am wrong._

ROADMAP.md: Mark hole punching on TCP and QUIC as done

---

ROADMAP.md

_As discussed in Paris, tracking the stream migration protocol in a separate roadmap item, instead of the "Unprecedented global connectivity" item. Note that the latter is being moved to "done" in https://github.com/libp2p/specs/pull/415._

ROADMAP.md: Add stream migration protocol

---

pubsub/gossipsub/gossipsub-v1.1.md

In eth2, you can't really be sure at which point you will have to subscribe from a topic.
So you when unsubscribe, you may have to resubscribe in the next 60 seconds
This causes a clash with the backoff, since every peer you had in your mesh when you unsubbed is now in your backoff, and forming an healthy mesh becomes tricky.
This is a bit of a corner case, but adding a setting to tune to unsub backoff really helps with this case, and doesn't cost anything, since if you stay out of the topic, you shouldn't get GRAFTed anyway.
We implemented it in nim-libp2p: https://github.com/status-im/nim-libp2p/pull/665
which drastically improved mesh health on our busy test nodes (2500 validators, which in eth2 term is stupidly big, but that's where the issue is most visible) (each validator causes …

Gossipsub: Unsubscribe backoff

---

pubsub/gossipsub/README.md

To the best of my knowledge, the Gossipsub implementation in rust-libp2p supports Gossipsub v1.1.
@AgeManning can you confirm? Am I missing something?
Follow up to https://github.com/libp2p/rust-libp2p/discussions/2825#discussioncomment-3430068.

pubsub/gossipsub: Update rust-libp2p supporting v1.1

---

tls/tls.md

tls: specify how the public key bytes are encoded

---

noise/README.md

The interface exposed by a libp2p Noise implementation is highly implementation-specific. Really, there’s no reason to even suggest something like `SecureInbound` and `SecureOutbound`, there are other ways to implement (and name) this that are equally conformant with this spec and interoperable with other implementations.
More importantly, the references made to early data in this section directly contradict what we’re planning to do with early data for WebTransport (#404), WebRTC (#412) and muxer negotiation (#446).

noise: remove interface definition

---

webtransport/README.md

**This PR is targeting #404, not master**.
This implements the proposal discussed in https://github.com/libp2p/specs/pull/404/files#r968836367.

webtransport: move certhash verification to the client

---

noise/README.md

Proto2 allows us to distinguish between unset and default values, which Proto3 doesn't. Since the protobuf we used for Noise was that simple, the serialization is compatible, so we can change to Proto2, even though some implementations interpreted the Protobuf defined here as Proto3.
I confirmed that a node running v0.22.0 (using a proto3 protobuf) can connect to a node using the proto2 protobuf, and vice versa.
```go
func main() {
h1, err := libp2p.New(
libp2p.ListenAddrStrings("/ip4/127.0.0.1/tcp/1234"),
libp2p.Security("noise", noise.New),
)
if err != nil {
log.Fatal(err)
}
fmt.Println("I am:", h1.ID())
h1.SetStreamHandler("/proto1", func(str network.Stream) {
data, err := io.ReadAll(str)
if err != nil {
log.Fatal(err)
}
fmt.Println("received data for proto1:", string(data))
})
select …
```

noise: specify proto2

---

noise/README.md

Fixes #450.
This PR removes the `data` field from the `NoiseHandshakePayload` protobuf, and adds an `extensions` field. `extensions` is `NoiseExtensions` protobuf, modeled after the extension registries that TLS and QUIC use.
By using a new ID (`data` was 3, `extensions` is 4), this change won’t break implementations that used early data (I’m not aware of any, but just in case).
I’ve added code points for WebTransport, WebRTC and Early Muxer Negotiation to this PR, mostly to demonstrate how this would look like. Given that none of the specs for these are merged yet, it might make sense to define an empty `NoiseExtensions` protobuf here, and have the respective PRs add their code point (we’ll have to deal with merge conflicts then). Let me know if I should make that change.

noise: introduce an extension registry

---

ROADMAP.md

Over the last couple of weeks, we've broken the early muxer negotiation into its own project (#446), and found an arguably nicer solution than proposed in the Protocol Select spec (#349). The change to move the security address into the multiaddr is already split out into a separate PR: #354.
With these two changes having been separated from Protocol Select, we save 2 RTTs during a TCP handshake, reducing the total latency to the bare minimum consumed by the components used (TCP: 1 RTT, security handshake: 1 RTT).
Implementing the rest of the Protocol Select spec now appears less pressing. The main additional benefits would be:
1. Slightly shorter protocol names, since the protocol string would be wrapped in a protobuf instead of being prefixed with `/multistream/1.0.0`. This saving of …

roadmap: rewrite the section about efficient handshakes

---

ROADMAP.md

Opt-in telemetry will only be of limited use, since there will be a very heavy selection bias (who turns on telemetry), as 99% of users never change the default settings.
Recent advances in cryptography, especially in multiparty computation, might allow us to develop a telemetry protocol that has privacy properties strong enough to justify turning on telemetry by default.
Providing a telemetry framework could be a major selling point of libp2p as library: Applications could use the same framework to gather application-level measurement results that come with the same strong privacy guarantees.

roadmap: rewrite the telemetry section

---

webrtc/README.md

WebRTC Transport (browser to server) has landed in rust-libp2p here https://github.com/libp2p/rust-libp2p/commit/a7148648858fe10e9ba4c2793c7e12392b49c0ab so there now exists one reference implementation.
In accordance with the [spec lifecycle](https://github.com/libp2p/specs/blob/master/00-framework-01-spec-lifecycle.md), we can update this spec from a Working Draft to a Candidate Recommendation.
* How will introducing [browser to browser](https://github.com/libp2p/specs/issues/475) affect the maturity level of this spec? Previously it was specified inside this document. Perhaps it should be specified in a separate document so it can have it's own maturity level/better separation of concerns.
* Any other criteria to consider before promoting from 1A to 2A?

chore: proposal to update WebRTC Browser to Server to Candidate Recommendation

---

pubsub/gossipsub/README.md

The added link goes to a full formal specification for GossipSub provided in ACL2s, an automated theorem proving environment.

Add link to formal specification of GossipSub

---

kad-dht/README.md

This PR updates the description of the Provider Record settings and most importantly proposes new values for both the republish interval and the expiration interval. The new proposed values are:
- republish interval to be set to 24hrs, from its current 12hrs
- expiration interval to be set to 48hrs, from its current 
and they are based on the comprehensive study published here: https://github.com/protocol/network-measurements/blob/master/results/rfm17-provider-record-liveness.md

New values for DHT Provider Record Republish and Expiration (22h/48h, RFM17)

---

ping/ping.md

- Following https://github.com/libp2p/docs/pull/263#discussion_r1039258841, clarifying protocol type by specifying "liveness check" as opposed to "request-response".
- General writing style updates.
- Update headings to sub-headings.

ping(fix): update type and enhance content

---

README.md
quic/README.md

Nothing fancy here. Creating this PR mostly to have a basis for the changes we’re planning for #498. Would appreciate getting this merged soon :)

add a basic QUIC spec

---

README.md
fetch/README.md
identify/README.md
kad-dht/README.md
plaintext/README.md
pubsub/README.md
pubsub/gossipsub/gossipsub-v1.0-old.md
pubsub/gossipsub/gossipsub-v1.0.md
pubsub/gossipsub/gossipsub-v1.1.md
relay/circuit-v1.md
relay/circuit-v2.md
rendezvous/README.md
tls/tls.md

Updates the README to recommend proto3. Makes all existing protobuf without an explicit syntax have `syntax="proto2"`.
See #465 for the discussion around this change.
Closes #465

Recommend proto3

---

ROADMAP.md

I'm not quite sure what our done criteria are (in this case, and in general).
In general, I'd consider an item "done" from a specs standpoint once the specs is stable, and an interoperable implementation has been rolled out. Usually, a single of our (big) implementations implementing a spec would fulfill that threshold.
For WebTransport, one could argue that interoperability is limited as long as we only have go-libp2p support, since WebTransport is a browser protocol. Maybe this means that we should wait for the js-libp2p release in this case.

roadmap: move WebTransport to Done section

---

relay/circuit-v2.md

Updates the circuit v2 spec to use proto3. This closes #509.

Update circuitv2 to proto3

---

tls/tls.md

This removes outdated `NamedCurve encoding usage` related paragraph from [tls.md](https://github.com/libp2p/specs/blob/master/tls/tls.md), resolves issue #510.

tls: remove outdated paragraph on use of NamedCurve encoding in certificates

---

relay/circuit-v2.md

Taking a suggestion from @aschmahmann from Slack to our specs:
>> can you confirm that everything relayed is encrypted ( not just authenticated )
>
> Yeah, this should be the case. When establishing a circuit-relayed connection the connection should get "upgraded" with security and multiplexing based on whatever you have supported for other unsecured transports like TCP (e.g. TLS/Noise and mplex/yamux).
> Although AFAICT this information is missing from https://github.com/libp2p/specs/blob/master/relay/circuit-v2.md although it is described in https://github.com/libp2p/specs/blob/master/relay/circuit-v1.md. It's probably worth assuming people aren't going to read the v1 spec if they're reading v2 unless explicitly directed to, so might want to copy in some of the context and assumptions …

docs(relay-v2): Document that relayed conn is upgraded with sec and mux

---

autonat/README.md

I don't like that this is the case, but that's what the Go implementation has been doing since forever, and for better or worse, we're stuck with it. The purpose of this PR is to document this behavior.
cc @sukunrt

autonat: document that the observed address may also be dialed

---

README.md
yamux/README.md

cc @marten-seemann @mxinden @wemeetagain 
The specification itself is a verbatim copy from https://github.com/hashicorp/yamux/blob/master/spec.md modulo formatting changes.
The only addition is the "Implementation considerations" section at the bottom where we document the ACK backlog of 256. To my knowledge, only `go-libp2p` implements this at the moment. `rust-yamux` still needs to implement this: https://github.com/libp2p/rust-yamux/issues/150. I am not sure about the status of this in `js-libp2p-yamux`?

Add yamux specification

---

relay/circuit-v2.md

The reservation expiration date is specified in seconds so be explicit about that in the spec in the same way we are explicit about the duration limit units.

circuitv2: specify timestamp units for reservation expiration

---

connections/README.md

feat(connections): clarify state management around supported protocols

---

relay/circuit-v2.md

This documents the rust-libp2p behaviour when more data than is allowed is transferred over a relayed connection.  js-libp2p will take the same approach.  go-libp2p may need to be updated.

circuitv2: clarify what to do when data limit is reached

---

autonat/autonat-v2.md

use a priority ordered list of addresses in autonat v2

---

autonat/autonat-v2.md

allow autonat v2 to dial all ips

---

ROADMAP.md
perf/perf.md

A simple protocol to run client-driven benchmarks inspired by https://datatracker.ietf.org/doc/html/draft-banks-quic-performance.

Introduce `perf` spec

---

ROADMAP.md

With https://github.com/libp2p/specs/pull/412 and
https://github.com/libp2p/specs/pull/497 merged, this roadmap item can be moved to "done".

chore(roadmap): move webrtc to done

---

http/README.md

This is slightly different from what I presented in the Moves The Bytes WG yesterday.
I introduced a `"services"` dict entry in the JSON object. This will allow us to add more configuration to the `libp2p.json` in the future (and not just protocol => path mapping).

http: use .well-known/libp2p.json for configuration

---

http/transport-component.md

This is meant to clarify what libp2p is expecting of the `/http` component and avoid folks creating conflicting interpretations of the component. This purposely does not include anything libp2p+http (but hints at it) with the goal of clarifying expectations of the `/http` component early.
Please take a look:
@lidel 
@marten-seemann 
@willscott 
@masih 
This was prompted by https://github.com/ipni/go-libipni/issues/42 + historical issues referenced in https://github.com/ipni/go-libipni/issues/42#issuecomment-1570503551

Document `/http`

---

http/README.md

Roughly, this PR:
* Removes sections that aren't directly relevant to an implementer.
* Proposes a Peer ID Authentication scheme that's similar to how we do authentication in WebTransport and WebRTC.
Besides the peer id authentication, I don't think there is anything new here compared to the `http` branch.
⚠️ Note: this targets the `http` branch. I would like to merge these changes into the `http` branch soon and continue discussion on that branch.

HTTP: Reformat the spec from the Point of View of an implementer + Peer ID Auth

---

pubsub/README.md

This updates an old note in the message ID section of the pubsub spec to reflect that go-libp2p-pubsub currently supports topic-specific message ID configuration, using [`WithTopicMessageIdFn`](https://pkg.go.dev/github.com/libp2p/go-libp2p-pubsub#WithTopicMessageIdFn).

fix(pubsub): remove "Implementation note" about setting `message_id_fn`

---

webrtc/webrtc.md

Connection establishment doesn't work if we don't create a channel before creating the SDP offer. 
Not exactly very helpful but some info on this SO question: https://stackoverflow.com/questions/38867763/why-i-have-to-open-data-channel-before-send-peer-connection-offer/38872920#38872920
js-libp2p already does this: https://github.com/libp2p/js-libp2p/blob/master/packages/transport-webrtc/src/private-to-private/handler.ts#L116-L119
go-libp2p: https://github.com/libp2p/go-libp2p/blob/webrtcprivate/transport/p2p/transport/webrtcprivate/transport.go#L242
I think this should be a part of the spec.

webrtc(browser-browser): specify init channel for connection establishment

---

webrtc/README.md

Specify closing datachannels by mutual agreement to ensure all data has been received by the remote before closing.
Refs: #575

webrtc: add FIN_ACK to close datachannels without data loss

---

webrtc/webrtc.md

The js-libp2p implementation of webrtc includes versioning for the [signalling protocol id](https://github.com/libp2p/js-libp2p/blob/9c67c5b3d0ab63c7a1a62f363ae732b300ef6b87/packages/transport-webrtc/src/private-to-private/transport.ts#L25) therefore existing nodes that support private-to-private would be utilizing a versioned protocol id. Whilst this may have been a mistake, it could be more prudent to introduce this versioning at the spec level as opposed to forcing existing nodes to synchronize upgrades.
1) There is already a precedent for versioning protocol ids across a variety of the protocols
2) The added benefit of future-proofing this protocol.
There is also the argument that we would be adjusting the spec in order to adapt to an implementation mistake, in most cases I would …

webrtc: introduce versioning for signalling protocol id

---

connections/inlined-muxer-negotiation.md

Based on this
```
The multiplexer to use is determined by picking the first item from the initiator's list that both parties support.
```
The chosen multiplexer to use will be `yamux/1.0.0`

muxer: correct inline muxer negotiation choice

---

http/README.md

This defines a multiaddr URI scheme. This would enable HTTP redirects to other hosts and resources. In Go, this would enable a single `http.RoundTripper` to work on any transport. In JS, we would be able to create a new [`Request`](https://developer.mozilla.org/en-US/docs/Web/API/Request) with this URI and use it with a custom [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) to make HTTP requests to any transport.
Example:
```
multiaddr:/ip4/1.2.3.4/udp/54321/quic-v1/p2p/12D.../httppath/.well-known%2Flibp2p
```
If we approve this, we should likely register this scheme with IANA. PL has registered other schemes in the past, so I think it is doable (`ipfs` and `ipns`).

libp2phttp: Define the multiaddr URI

---

http/README.md
noise/README.md

This PR adds a specification for libp2p+HTTP. 
It builds on countless discussions with various people interested in this topic, and incorporates the thinking outlined in #477 and #481.
Peer ID authentication over HTTP is deferred to a separate proposal: https://github.com/libp2p/specs/pull/564. That work is put on hold for now until we find a strong use case for it.
The work was started by Marten & Marco, and continued by @MarcoPolo. Recent edits are from @MarcoPolo .

add HTTP spec

---

yamux/README.md

- Flow control is ruled per stream via window updates
- Initial windows size is 262144 bytes

Clarify yamux stream flow control terminilogy

---

websockets/README.md

The spec is missing example with `/sni/` which is how every `libp2p.direct` from [AutoTLS in Kubo >=0.32.0-rc1](https://github.com/ipfs/kubo/issues/10560) will look like. 
This PR adds it.

docs(websockets): include explicit /sni/ example

---

pubsub/gossipsub/README.md

I've noticed that despite GossipSub 1.2 spec being merged to the specs-repo, it is not present in the summary of the README file. This PR update the summary with the current status of the development.
Open questions:
- I'm aware that the Sigp had IDONTWANT implemented in Lighthouse's rust-libp2p, but I couldn't find any link in the `rust-libp2p` repo. Leaving the question mark on `rust-libp2p` until @AgeManning or @jxs  can confirm the status. 
CC: @vyzo

Add gossipsub 1.2 links to the README

---

kad-dht/README.md

* Note that the bootstrap process description is [just a suggestion](https://github.com/libp2p/specs/blob/b5f7fce29b32d4c7d0efe37b019936a11e5db872/kad-dht/README.md?plain=1#L365-L368)
> The below is one possible algorithm to bootstrap. Implementations may diverge from this base algorithm as long as they adhere to the wire format and keep their routing table up-to-date, especially with peers
closest to themselves.
* Update default bootstrap interval to 10 minutes ([go-libp2p-kad-dht](https://github.com/libp2p/go-libp2p-kad-dht/blob/88720a04b40153855cf8d5e27e8a4a6bddb3092a/internal/config/config.go#L126), [IPFS doc](https://docs.ipfs.tech/concepts/dht/#routing-tables))
* Replace _a random peer ID_ with _a random peer ID for every non-empty routing table's k-bucket_.
* The random peer ID has …

kad: clarify bootstrap process

---

kad-dht/README.md

In this [PR](https://github.com/libp2p/go-libp2p-kad-dht/pull/605), the default value of the concurrency parameter is updated

docs(dht): Update default concurrency parameter

---

http/peer-id-auth.md

There should not be a comma after the authentication scheme name.

fix: http auth header typo

---

tls/tls.md

Adds note about which ALPN protocol to use and links to spec for inlining muxer negotiation.
Avoids things like https://github.com/libp2p/jvm-libp2p/issues/404
Fixes #607
Fixes #496

docs: add ALPN section to TLS and link to inlined muxer negotiation

---

http/peer-id-auth.md

Where a bearer token is returned to the client for future use, optionally include an `expires` field which indicates the latest time that it will be treated as valid.
The server is free to expire tokens at any time so this field is purely advisory.
Fixes #674

docs: adds an expires field to the bearer token response
